export { default as HomePage } from './HomePage'
export { default as FavoritesPage } from './FavoritesPage'
export { default as MoviesPage } from './MoviesPage'
export { default as TVSeriesPage } from './TVSeriesPage'
export { default as DetailPage } from './DetailPage'
